### ISSUE TITLE
[BUG] onnxruntime error

### ISSUE THREAD

**Issue by yundaehyuck** [SKTBrain/KoBERT#101]
## 🐛 Bug

현재(2023/04/28, 오후 12:42경) colab에서 

!pip install git+https://git@github.com/SKTBrain/KoBERT.git@master

수행할시 onnxruntime 버전이 안맞다며 에러가 납니다

## To Reproduce

버그를 재현하기 위한 재현절차를 작성해주세요.

1. -
2. -
3. -

## Additional context

ERROR: Could not find a version that satisfies the requirement onnxruntime<=1.8.0,==1.8.0 (from kobert) (from versions: 1.12.0, 1.12.1, 1.13.1, 1.14.0, 1.14.1)
ERROR: No matching distribution found for onnxruntime<=1.8.0,==1.8.0

**Comment by Allgot** [comment]
저도 같은 문제를 겪고 있는데, 제가 파악한 바로는 colab 업데이트로 인한 호환성 오류로 보입니다.

22시간 전에 colab의 python 버전이 3.10로 올라갔는데, 이 3.10 버전부터 koBERT가 요구하는 onnxruntime의 버전을 더이상 지원하지 않는 것이 원인입니다.

colab의 python 버전을 낮추시거나 koBERT를 조금 수정하여 최신의 onnxruntime 버전과 호환되게 만드셔야 할 것 같습니다.

**Comment by yundaehyuck** [comment]
감사합니다 선생님!

**Comment by grulla79** [comment]
혹시 질문자님이 해결하셨다면 어떻게 해결하셨는지 알 수 있을까요?
