### ISSUE TITLE
BERT Dataset 'not a string' error

### ISSUE THREAD

**Issue by zozo170610** [SKTBrain/KoBERT#105]
개발환경: colab

Hugging Face 방법으로 진행.

아래의 방법으로 진행 시

맨 아래의 그림에 나타난 에러가 발생합니다. 

![image](https://github.com/SKTBrain/KoBERT/assets/123877121/b234d1ac-ee3b-4e17-9c51-1fadd89d5197)
![image](https://github.com/SKTBrain/KoBERT/assets/123877121/e0be97a5-5e7d-4cc6-96a9-425d214ee74b)
![image](https://github.com/SKTBrain/KoBERT/assets/123877121/d17cc152-f5ee-4d4e-b71f-ddb7c9ec7515)

**Comment by jaesung-eee** [comment]
어떻게 해결하셨는지 여쭐 수 있을까요?
