### ISSUE TITLE
별도 학습된 토크나이저 사용

### ISSUE THREAD

**Issue by robinsongh381** [SKTBrain/KoBERT#12]
KoBERT 입력으로 넣어주는 문장의 토크나이저를 KoBERT에서 제공한 토크나이저가 아니라 별도로 학습된 sentencepiece 토크나이저 사용을 할 수 있나요 ?

위와 같이 시도해보니 중간에 에러가 발생합니다

**Comment by haven-jeon** [comment]
네 당연히 에러가 납니다. 
BERT 네트워크 아키텍를 보시면 네트워크 파라메터랑 vocabulary가 하나의 pair라는걸 아실 수 있을겁니다. 
네트워크 앞부분 token id embedding만 보더라도 토큰이 달라지만 다른 값을 가져야 되겠죠.
