### ISSUE TITLE
기본 모델 레이어 변경

### ISSUE THREAD

**Issue by robinsongh381** [SKTBrain/KoBERT#14]
안녕하세요

좋은 모델 배포해주셔서 감사의 말씀 먼저 전합니다

KoBert 구조는 [Attention-Feed_Forward]  x 12 의 모델 구조로 이루어져 있습니다 (add-norm 생략)
모델 구조를 각 레이어 마지막에 (예를들어) RNN을 추가하여 ( [Attention-Feed_Forward-**RNN**] x 12 구조로 변경가능한지, 가능하다면 어떻게 할지 궁금하여 문의드립니다

감사합니다

**Comment by haven-jeon** [comment]
감사합니다.

안타깝게도 위 질문은 KoBERT와 관련이 없어 보이네요. 참고로 모든 모델은 네트워크 구조 변경이 가능하나 변경되면 재학습이 불가피합니다.

**Comment by robinsongh381** [comment]
안타깝게도 제 질문의 의도를 잘못 파악하신거 같습니다, 당황스럽네요.

KoBERT 발전을 위해서라도 다양한 질문을 수용하길 바랍니다

**Comment by haven-jeon** [comment]
@robinsongh381  
KoBERT는 BERT 논문을 기반으로 한국어 데이터로 학습이 된 모델이고 해당 레포는 모델의 학습 결과를 대중에게 제공하기 위해 만들어 졌습니다. 버트 모델 아케텍처 자체에 대한 논의는 발전적인 질문이 될 수 있으나, 해당 레포의 목적과는 다소 거리가 있어 그렇게 답변을 드린것이니 답변에 대한 오해 없었으면 좋겠습니다. ^^
