### ISSUE TITLE
pre-training 작업을 어떻게 진행하셨는 지 알 수 있을까요? 

### ISSUE THREAD

**Issue by ghk829** [SKTBrain/KoBERT#15]
pre-training 작업을 어떻게 진행하셨는 지 알 수 있을까요?
가능하다면 소스레벨로 받을 수 있을까요??

**Comment by haven-jeon** [comment]
BERT 학습을 위해 아래 코드를 참고하여 직접 구현(MXNet)해 학습을 진행하였습니다. 

https://github.com/google-research/bert

**Comment by messitrip** [comment]
@haven-jeon 
빠른 답변주셔서 너무 감사합니다.
소스상 transformers에서 import해서 huggingface 모듈로 한 줄 알고 여쭤봤는데 자체 구현하신 거군요!!
너무 대단하시고 감사합니다 :)

**Comment by haven-jeon** [comment]
KoBERT 초기 학습시에는 구글 코드 이외에는 학습 코드가 없어서 직접 구현했지만, 지금은 주요 프레임웍에서도 학습 코드를 직접 구현해 오픈된 코드들이 있는걸로 알고 있습니다. 그러한 코드를 참고하셔도 될듯 합니다. 
감사합니다.
