### ISSUE TITLE
transformers 라이브러리에 맞춘 예제 코드 변경

### ISSUE THREAD

**Issue by monologg** [SKTBrain/KoBERT#16]
안녕하세요:)

kobert 라이브러리에서 얼마 전에 pytorch_pretrained_bert에서 transformers로 바꾸면서 README의 예제대로 하면 결과가 동일하게 나오지 않아 확인해보았습니다.

1. forward 인자 순서 변경
- `pytorch_pretrained_bert`: input_ids, token_type_ids, input_mask 순
- `transformers`: input_ids, input_mask, token_type_ids 순

https://github.com/huggingface/transformers/blob/73028c5df0c28ca179fbe565482a9c2143787f61/src/transformers/modeling_bert.py#L636-L646

2. return 값 변경
기존 `pytorch_pretrained_bert`에서는 **12 layer의 값을 모두 리턴**했지만, `transformers`에서는 **마지막 layer**의 값만 리턴합니다.

https://github.com/huggingface/transformers/blob/73028c5df0c28ca179fbe565482a9c2143787f61/src/transformers/modeling_bert.py#L648-L671

두 가지 부분을 수정하여 확인하였고, 기존 README.md의 예제와 동일한 결과가 나오는 것을 확인했습니다.

해당 부분 관련하여 PR 올렸습니다:)

감사합니다!

**Comment by haven-jeon** [comment]
merge 되었습니다!
