### ISSUE TITLE
안녕하세요 잘보았습니다.

### ISSUE THREAD

**Issue by KKodi-Sera** [SKTBrain/KoBERT#18]
안녕하세요. 잘보았습니다.

혹시 파이썬을 다루는데 있어 아직 초보라 그런데 나와있는 colab을 하나하나 모두 실행시켜야 하나요?

그리고 colab은 작성하고 난후 시간이 지나면 입력된 변수 값들이 모두 제거되지 않나요?

그리고 혹시 jupyter notebook 등으로 작업하면 어떤 순서대로 작업해야 하는지 예제를 알 수 있을까요??

**Comment by haven-jeon** [comment]
https://github.com/SKTBrain/KoBERT/tree/master/scripts/NSMC 에 예제가 있습니다. 

감사합니다.
