### ISSUE TITLE
안녕하세요. 잘보았습니다.

### ISSUE THREAD

**Issue by KKodi-Sera** [SKTBrain/KoBERT#19]
안녕하세요. 훌륭한 학습 모델을 개발해주셔서 너무나 감사합니다

다름이 아니오라 엑셀파일에 있는 1개의 열에 존재하는 모든 문장을 

긍정/부정 분류를 해서 그 결과값을 엑셀 파일로 얻고 싶은데 이럴때는 어떤 함수를 입력해야하나요?

**Comment by haven-jeon** [comment]
KoBERT는 언어모델로 긍정부정 분류에 대한 직접적인 기능을 제공하지 않고 있습니다.
하지만 https://github.com/SKTBrain/KoBERT/blob/master/scripts/NSMC/naver_review_classifications_pytorch_kobert.ipynb 스크립트를 기반으로 파인튜닝 이후 원하시는 방향으로 모델을 사용하실 수 있을 겁니다. 

감사합니다.
