### ISSUE TITLE
Kobert로 squad 문제를 풀려고합니다.

### ISSUE THREAD

**Issue by junho-one** [SKTBrain/KoBERT#2]
Kobert로 squad dataset 형태의 문제를 풀려고하는데 학습을 하려하는데 어떻게 학습 시켜아 할 지 모르겠는데 도움을 좀 주실 수 있을까요??

hugging face의 run_squad와 결합하여 학습을 시켜보려고 노력했지만 실패했습니다..

**Comment by haven-jeon** [comment]
https://github.com/lyeoni/KorQuAD 와 같은 여러 공개 자료를 참고하시면 어떨까 합니다.

**Comment by junho-one** [comment]
네!! 친절한 답변 감사드립니다.
한번 이 레포를 참고해서 변형을 해보겠습니다.
오늘 남은 하루도 수고하십시오.

2019년 10월 15일 (화) 오후 3:45, Heewon Jeon(gogamza) <notifications@github.com>님이
작성:

**Comment by haven-jeon** [comment]
감사합니다!

**Comment by junho-one** [comment]
안녕하세요
알려주신 사이트를 참고해봤는데, 질문이 있어서 올립니다.
hugging face에 run_squad를 했을 때와 똑같은 에러가 나오는데

위 사이트에서는 모델에 인풋값을
model(input_ids, segment_ids, input_mask, start_positions, end_positions)
로 주는데

Kobert 모델에 인풋값은
model(input_ids, token_type_ids, input_mask)
이런 형식으로 주더라고요

이렇게 인풋에 차이가 나는데 어떻게 맞춰줄 수 있는지 조언을 좀 구할 수 있을까요?
