### ISSUE TITLE
KoBERT 사용에 대한 질문

### ISSUE THREAD

**Issue by cpark321** [SKTBrain/KoBERT#20]
안녕하세요. 
kobert를 사용하면 sentence에서 각 token들을 contextual embedding 한 것을  확인할 수 있었습니다. 
(기본 모델의 경우 각 token 당 768차원)
구글BertForMaskedLM의 경우와 같이 masked sentence를 입력하고 masked 된 단어를 전체 vocab에서 예측하는 LM로도 사용할 수 있는지요?
KoBERT에서는 768차원 hidden state만 출력 되는 것 같아 LM 기능도 제공되는지 여쭈어봅니다.

**Comment by haven-jeon** [comment]
네 말씀하신 방식대로 활용 가능합니다.

https://huggingface.co/transformers/model_doc/bert.html?highlight=bert%20lm#transformers.BertForMaskedLM

만일 생성 쪽으로 모델이 필요하시다면 https://github.com/SKT-AI/KoGPT2 를 추천드립니다. 

감사합니다.

**Comment by haven-jeon** [comment]
별다른 답변이 없어 해당 이슈는 클로즈 합니다.
