### ISSUE TITLE
Sentencepiece 한글 초성/중성 에러

### ISSUE THREAD

**Issue by robinsongh381** [SKTBrain/KoBERT#21]
안녕하세요

`tokenizer = KoBertTokenizer.from_pretrained('monologg/kobert') `처럼 토크나이저를 가져와서

"한국어로는 안돼??ㅋ' 의 문장을 `tokenizer.tokenize( )` 하게 되면 다음과 같은 아웃풋이 나옵니다
![image](https://user-images.githubusercontent.com/42966248/82807650-2680ad80-9ec3-11ea-9bbc-83fa771913a8.png)

하지만 마지막 값은 한글 초성 'ㅋ'과 다른 값입니다. (작은 'ㅋ')

실제로 `tokenizer.convert_tokens_to_ids('ㅋ')` 하게 되면 unknown 값인 0이 리턴되고, 작은 'ㅋ' 값을 넣으면 정상적으로 나옵니다.
![image](https://user-images.githubusercontent.com/42966248/82807892-a7d84000-9ec3-11ea-8fd3-0e2174b28e67.png)
![image](https://user-images.githubusercontent.com/42966248/82807916-ba527980-9ec3-11ea-9f48-b15c625ad4e6.png)

이 때문에 다음과 같은 상황에서 에러가 발생합니다

![image](https://user-images.githubusercontent.com/42966248/82807838-8c6d3500-9ec3-11ea-9f99-cdae93900c17.png)

이는 초성뿐만아니라 중성에서도 발생합니다

**Comment by haven-jeon** [comment]
KoBERT에서 쓰인 토크나이저는 `https://github.com/google/sentencepiece`로 NFKC 정규화를 기본으로 적용하게 됩니다. 그 때문에 현상으로 보이며, 입력 텍스트를 동일하게 정규화 하면 해결됩니다.

```python
import unicodedata
unicodedata.normalize('NFKC', '한국어로는 안되?ㅋ') 
'한국어로는 안되?ᄏ'
```

**Comment by robinsongh381** [comment]
네 감사합니다 :)
