### ISSUE TITLE
혹시 사용법 같은 자세한 문서 같은게 없을까요?

### ISSUE THREAD

**Issue by dbwodlf3** [SKTBrain/KoBERT#22]
만약에 문서가 있다면 큰 도움이 될 것 같아서..!

**Comment by kimsijin33** [comment]
KoBERT 사용방법 문서같은 것을 구하셨나요?

**Comment by dbwodlf3** [comment]
> #dbwodlf3 님 KoBERT 사용방법 문서같은 것을 구하셨나요?

아니오. 해당 프레임워크에 익숙하신 분들에게는 너무나도 상식적이고 자연스러운 부분이어서 딱히 그에 대한 자세한 문서를 작성하지 않은 것 같습니다.

**Comment by kimsijin33** [comment]
> 해당 프레임워크에 익숙하신 분들에게는 너무나도 상식적이고 자연스러운 부분이어서 딱히 그에 대한 자세한 문서를 작성하지 않은 것 같습니다.

이 프레임워크를 서버에 구현하는 방법을 좀 알 수 있을까요? 
서버에 파일들 올려놓고 현재는 콜랩에서 테스트 해보고 있는데요 

궁금한 것은 
데이터 셋이이 있으면 이를 학습시켜서 모델을 만드는 방법도 (코드에 다 나와 있는거죠?)

제 가 데이터 인풋을 하면 결과가 나오는 이런 프로세스를 구현 하고 싶은데요

실제적으로 서버에 딥러닝 모델을 구현하는 것은  처음이라 전체적으로 궁금한게 많습니다.

**Comment by kimsijin33** [comment]
> > #dbwodlf3 님 KoBERT 사용방법 문서같은 것을 구하셨나요?
> 
> 아니오. 해당 프레임워크에 익숙하신 분들에게는 너무나도 상식적이고 자연스러운 부분이어서 딱히 그에 대한 자세한 문서를 작성하지 않은 것 같습니다.

여기있는 코드와 소스를 가지고 실제 서버에 모델을 구현할 수 있는거죠?

텍스트 데이터 를 넣으면 뭔가 아웃풋(Result 결과) 가 텍스트로 나오는 이런것을 구현 하려고 하는데요 
여기 코드로 가능 할까요?

**Comment by dbwodlf3** [comment]
> > > #dbwodlf3 님 KoBERT 사용방법 문서같은 것을 구하셨나요?
> > 
> > 
> > 아니오. 해당 프레임워크에 익숙하신 분들에게는 너무나도 상식적이고 자연스러운 부분이어서 딱히 그에 대한 자세한 문서를 작성하지 않은 것 같습니다.
> 
> 여기있는 코드와 소스를 가지고 실제 서버에 모델을 구현할 수 있는거죠?
> 
> 텍스트 데이터 를 넣으면 뭔가 아웃풋(Result 결과) 가 텍스트로 나오는 이런것을 구현 하려고 하는데요
> 여기 코드로 가능 할까요?

저는 해보지는 않았지만 아마 가능하리라고 예상합니다.

https://github.com/SKTBrain/KoBERT/tree/master/scripts/NSMC

해당폴더의 파일이 Example 파일입니다.

**Comment by kimsijin33** [comment]
> > > > #dbwodlf3 님 KoBERT 사용방법 문서같은 것을 구하셨나요?
> > > 
> > > 
> > > 아니오. 해당 프레임워크에 익숙하신 분들에게는 너무나도 상식적이고 자연스러운 부분이어서 딱히 그에 대한 자세한 문서를 작성하지 않은 것 같습니다.
> > 
> > 
> > 여기있는 코드와 소스를 가지고 실제 서버에 모델을 구현할 수 있는거죠?
> > 텍스트 데이터 를 넣으면 뭔가 아웃풋(Result 결과) 가 텍스트로 나오는 이런것을 구현 하려고 하는데요
> > 여기 코드로 가능 할까요?
> 
> 저는 해보지는 않았지만 아마 가능하리라고 예상합니다.
> 
> https://github.com/SKTBrain/KoBERT/tree/master/scripts/NSMC
> 
> 해당폴더의 파일이 Example 파일입니다.

 답변 정말 감사드립니다. 

이게 그럼 어떤 결과를 가져다 주는 모델인가요? 
영어 -> 한글 번역?

**Comment by dbwodlf3** [comment]
BERT 모델의 한국어버전이라고 이해하고 있습니다.
정확한 정보는 관련 논문을 읽어보시는게 좋을 것 같고.
https://ebbnflow.tistory.com/151 이 글을 참고하시면 도움이 될 것 같습니다.

영어 -> 한글 번역. 같은 어떤 특별한 용도가 있는 "프로그램" 이라기 보다는.

"머신러닝으로 학습된 언어 모델"이라고 이해하시는게 도움이 될 것 같습니다.
라이브러리 같은 느낌으로. 나머지 이제 구체적인 서비스나 기능은, 이 KoBERT을 잘 사용해서 구현할 프로그래머의 몫이구요.

**Comment by kimsijin33** [comment]
> BERT 모델의 한국어버전이라고 이해하고 있습니다.
> 정확한 정보는 관련 논문을 읽어보시는게 좋을 것 같고.
> https://ebbnflow.tistory.com/151 이 글을 참고하시면 도움이 될 것 같습니다.
> 
> 영어 -> 한글 번역. 같은 어떤 특별한 용도가 있는 "프로그램" 이라기 보다는.
> 
> "머신러닝으로 학습된 언어 모델"이라고 이해하시는게 도움이 될 것 같습니다.
> 라이브러리 같은 느낌으로. 나머지 이제 구체적인 서비스나 기능은, 이 KoBERT을 잘 사용해서
> 구현할 머신러닝 프로그래머의 몫이구요.

답변 정말 감사드립니다. ^^ (_._) 꾸벅

**Comment by kimsijin33** [comment]
> BERT 모델의 한국어버전이라고 이해하고 있습니다.
> 정확한 정보는 관련 논문을 읽어보시는게 좋을 것 같고.
> https://ebbnflow.tistory.com/151 이 글을 참고하시면 도움이 될 것 같습니다.
> 
> 영어 -> 한글 번역. 같은 어떤 특별한 용도가 있는 "프로그램" 이라기 보다는.
> 
> "머신러닝으로 학습된 언어 모델"이라고 이해하시는게 도움이 될 것 같습니다.
> 라이브러리 같은 느낌으로. 나머지 이제 구체적인 서비스나 기능은, 이 KoBERT을 잘 사용해서
> 구현할 머신러닝 프로그래머의 몫이구요.

한가지 더 여쭙겠습니다. 
0에 가까우면 부정이고 1에 가까우면 긍정인 찾는것 과 같은건데 
여기서 이런 기준이 하나 인데 이런것을 
여러개 둘 수 있나요? 한 20개 정도 
그런 것을 multiclass classification 이라고 하나요?

**Comment by kimsijin33** [comment]
> BERT 모델의 한국어버전이라고 이해하고 있습니다.
> 정확한 정보는 관련 논문을 읽어보시는게 좋을 것 같고.
> https://ebbnflow.tistory.com/151 이 글을 참고하시면 도움이 될 것 같습니다.
> 
> 영어 -> 한글 번역. 같은 어떤 특별한 용도가 있는 "프로그램" 이라기 보다는.
> 
> "머신러닝으로 학습된 언어 모델"이라고 이해하시는게 도움이 될 것 같습니다.
> 라이브러리 같은 느낌으로. 나머지 이제 구체적인 서비스나 기능은, 이 KoBERT을 잘 사용해서
> 구현할 머신러닝 프로그래머의 몫이구요.

아래 사이트 보면
https://github.com/monologg/KoBERT-nsmc

이건 학습 하는 거고
$ python3 main.py --model_type kobert --do_train --do_eval

아래는 모델 돌려서 아웃풋을 내는 건데
$ python3 predict.py --input_file {INPUT_FILE_PATH} --output_file {OUTPUT_FILE_PATH} --model_dir {SAVED_CKPT_PATH}

여기 소스로 학습한 모델은 어느 경로에 저장되나요?

그리고 학습 모델 만들고 result 할 때 사용하는 main.py, predict.py 파일은 어느 경로에 있나요? python 에 기본적으로 가지고 있는 파일인가요?

실제 우분투 컴퓨터 환경에 올릴 수 있는지도 궁금합니다.

감사합니다.

**Comment by dbwodlf3** [comment]
> > BERT 모델의 한국어버전이라고 이해하고 있습니다.
> > 정확한 정보는 관련 논문을 읽어보시는게 좋을 것 같고.
> > https://ebbnflow.tistory.com/151 이 글을 참고하시면 도움이 될 것 같습니다.
> > 영어 -> 한글 번역. 같은 어떤 특별한 용도가 있는 "프로그램" 이라기 보다는.
> > "머신러닝으로 학습된 언어 모델"이라고 이해하시는게 도움이 될 것 같습니다.
> > 라이브러리 같은 느낌으로. 나머지 이제 구체적인 서비스나 기능은, 이 KoBERT을 잘 사용해서
> > 구현할 머신러닝 프로그래머의 몫이구요.
> 
> 한가지 더 여쭙겠습니다.
> 0에 가까우면 부정이고 1에 가까우면 긍정인 찾는것 과 같은건데
> 여기서 이런 기준이 하나 인데 이런것을
> 여러개 둘 수 있나요? 한 20개 정도
> 그런 것을 multiclass classification 이라고 하나요?

예. 응용하여서 만든 모델의 아웃풋 노드가 하나라면, 말씀하시는 '기준'이 한가지 일 수 있습니다.
아웃풋 노드가 1억개면 1억개일 수 있습니다.
그렇지만 해당 데이터셋에서 가장많이 나타나는 Feature 가 두드러지 않는다면 무의미한 학습이 될 것 입니다.(큰 수의 법칙에 따라서.)

학습을 하는데 중요한 것은 모델이기도 하지만, 데이터도 무척이나 중요합니다.

**Comment by dbwodlf3** [comment]
> > BERT 모델의 한국어버전이라고 이해하고 있습니다.
> > 정확한 정보는 관련 논문을 읽어보시는게 좋을 것 같고.
> > https://ebbnflow.tistory.com/151 이 글을 참고하시면 도움이 될 것 같습니다.
> > 영어 -> 한글 번역. 같은 어떤 특별한 용도가 있는 "프로그램" 이라기 보다는.
> > "머신러닝으로 학습된 언어 모델"이라고 이해하시는게 도움이 될 것 같습니다.
> > 라이브러리 같은 느낌으로. 나머지 이제 구체적인 서비스나 기능은, 이 KoBERT을 잘 사용해서
> > 구현할 머신러닝 프로그래머의 몫이구요.
> 
> 아래 사이트 보면
> https://github.com/monologg/KoBERT-nsmc
> 
> 이건 학습 하는 거고
> $ python3 main.py --model_type kobert --do_train --do_eval
> 
> 아래는 모델 돌려서 아웃풋을 내는 건데
> $ python3 predict.py --input_file {INPUT_FILE_PATH} --output_file {OUTPUT_FILE_PATH} --model_dir {SAVED_CKPT_PATH}
> 
> 여기 소스로 학습한 모델은 어느 경로에 저장되나요?
> 
> 그리고 학습 모델 만들고 result 할 때 사용하는 main.py, predict.py 파일은 어느 경로에 있나요? python 에 기본적으로 가지고 있는 파일인가요?
> 
> 실제 우분투 컴퓨터 환경에 올릴 수 있는지도 궁금합니다.
> 
> 감사합니다.

해당 코드를 작성하신 분에게 물으시는 것이 좋을 것 같습니다.

저도 잘 몰라서..;; ^^;
