### ISSUE TITLE
Kobert 모델 구조 변경 질문

### ISSUE THREAD

**Issue by qkrguswn2401** [SKTBrain/KoBERT#23]
먼저 Kobert를 배포해주신것에 감사합니다.  
현재 배포에 주신 모델은 Sentence 모델에 더 적합다고 생각합니다.
word 단위로 하기위하여 model에서 나오는 output dimension을 줄일수있는지 궁금합니다

**Comment by haven-jeon** [comment]
[CLS] [TOK1] [TOK2].... [TOKN] 과 같은 형태로 임베딩을 얻을 수 있습니다. 
[CLS] 만을 사용한다면 sentence 임베딩이 되겠지만, 개별 토큰임베딩 역시 출력으로 받을 수 있기 때문에 워드 단위로도 가능합니다.

**Comment by haven-jeon** [comment]
5일동안 추가 코멘트가 없어 해당 이슈는 클로즈 하겠습니다.
