### ISSUE TITLE
네이버 영화 리뷰 분류 콜랩 코드에서 에러가 발생합니다.

### ISSUE THREAD

**Issue by sociengineer** [SKTBrain/KoBERT#25]
안녕하세요, 예제 코드를 돌리는 중에 에러가 발생하여 올립니다.
naver_review_classifications_gluon_bert.ipynb을 돌리는 중에

bert_base, vocab = get_mxnet_kobert_model(use_decoder=False, use_classifier=False, ctx=ctx)에서
다음과 같은 에러가 발생합니다.

TypeError                                 Traceback (most recent call last)
<ipython-input-11-0073a775feeb> in <module>()
----> 1 bert_base, vocab = get_mxnet_kobert_model(use_decoder=False, use_classifier=False, ctx=ctx)

1 frames
/usr/local/lib/python3.6/dist-packages/kobert/mxnet_kobert.py in get_kobert_model(model_file, vocab_file, use_pooler, use_decoder, use_classifier, ctx)
     90                           output_attention=False,
     91                           output_all_encodings=False,
---> 92                           use_residual=predefined_args['use_residual'])
     93 
     94     # BERT

TypeError: __init__() got an unexpected keyword argument 'attention_cell'

어떻게 고쳐야 하는지 알려주실 수 있나요?

**Comment by haven-jeon** [comment]
올려주신지 시간이 너무 오래 경과되었는데, 이제 확인 했습니다. 버전 문제일거 같은데, 더 확인해 보겠습니다. 
감사합니다.

**Comment by snoop2head** [comment]
@haven-jeon 
저도 [naver_review_classifications_gluon_kobert.ipynb](https://github.com/SKTBrain/KoBERT/blob/master/scripts/NSMC/naver_review_classifications_gluon_kobert.ipynb) 파일에서 유사한 에러를 얻었습니다
[📁 해당 콜랩 파일](https://colab.research.google.com/drive/132_PIL7eje2iFzlT9fINZAANycsM1YYy?usp=sharing)


```
## Loading KoBERT
In [ ]: ctx = mx.gpu()
In [ ]: bert_base, vocab = get_mxnet_kobert_model(use_decoder=False, use_classifier=False, ctx=ctx)
---------------------------------------------------------------------------------------------------------
[██████████████████████████████████████████████████]
[██████████████████████████████████████████████████]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-0073a775feeb> in <module>()
----> 1 bert_base, vocab = get_mxnet_kobert_model(use_decoder=False, use_classifier=False, ctx=ctx)

1 frames
/usr/local/lib/python3.6/dist-packages/kobert/mxnet_kobert.py in get_kobert_model(model_file, vocab_file, use_pooler, use_decoder, use_classifier, ctx)
     90                           output_attention=False,
     91                           output_all_encodings=False,
---> 92                           use_residual=predefined_args['use_residual'])
     93 
     94     # BERT

TypeError: __init__() got an unexpected keyword argument 'attention_cell'
```

**Comment by haven-jeon** [comment]
8338f49434b

6355a1354

**Comment by haven-jeon** [comment]
최근 gluonnlp API가 변경이 있었네요. ^^

**Comment by snoop2head** [comment]
@haven-jeon 아 그렇군요... 이제 정상적으로 작동합니다! 감사합니다 ㅎㅎ

**Comment by haven-jeon** [comment]
넵.. 감사합니다. 해당 이슈는 클로즈 하겠습니다.
