### ISSUE TITLE
KoBERTSUM 생성 계획 문의

### ISSUE THREAD

**Issue by skim-muhayu** [SKTBrain/KoBERT#27]
KoBERT를 잘 사용하고 있습니다. 감사합니다.  
Document Summarization 분야에서 BertSumExt, BertSumExtAbs 가 상위 1-2위인데, 이 모델을 사용하려면 BERT가 BERTSUM 형태로 빌드되어 있어야 해서 한글 버전 BERTSUM이 배포되기를 조심스럽게 희망합니다.
KoBERTSUM이 생성 배포될 수 있을지 문의드립니다.
(참고) https://arxiv.org/pdf/1908.08345.pdf   (BERTSUM extends BERT by inserting multiple [CLS] symbols to learn sentence representations and using interval segmentation embeddings (illustrated in red and green color) to distinguish multiple sentences.))

**Comment by haven-jeon** [comment]
내부적으로 KoBERT 등을 이용한 한글요약에 대한 리서치를 하고 있어서 조만간 긍정적인 피드백을 드릴 수 있을거라 예상합니다. ^^
