### ISSUE TITLE
새로운 문장 추론을 하는 것에 관해 문의드립니다.

### ISSUE THREAD

**Issue by sociengineer** [SKTBrain/KoBERT#28]
안녕하세요 KoBERT 구현해주신 덕분에 이것저것 해보고 있는 중입니다.
NSMC 데이터로 높은 성능을 달성해서 이를 새로운 문장에 테스트를 해보고 싶습니다.
BERTClassifier 클래스에 forward함수의 인자를 맞춰서 집어넣어주면 된다고 생각하는데 이렇게 하는 것이 맞나요?
특히 valid_length를 만들기가 어려운데, 이건 데이터로더에서만 만들 수 있는건지 궁금합니다.

감사합니다.

**Comment by haven-jeon** [comment]
> BERTClassifier 클래스에 forward함수의 인자를 맞춰서 집어넣어주면 된다고 생각하는데 이렇게 하는 것이 맞나요?
네, 맞습니다. 맞춰서 입력해주면 됩니다. 

글로 유추해 보건데, gluonnlp 기반으로 하시는거 같습니다. 관련 글이 있으니 참고 바랍니다.
https://gluon-nlp.mxnet.io/examples/sentence_embedding/bert.html

**Comment by sociengineer** [comment]
맞춰서 입력해서 해결했습니다~ 감사합니다
