### ISSUE TITLE
Is there any published paper describing your work?

### ISSUE THREAD

**Issue by ilya-palachev** [SKTBrain/KoBERT#29]
Hello,

First of all, thank you for publishing this repository. Is there any published paper describing your work? I mean a paper in some journal or conference proceedings. This information would help to understand your work a lot.

Thanks in advance!

**Comment by haven-jeon** [comment]
In addition to those mentioned in BERT paper, the parts that were conducted while training Korean are specified in README.md.

**Comment by ilya-palachev** [comment]
So, you don't have any published papers either in Korean or in English, right?

**Comment by haven-jeon** [comment]
Yes!

**Comment by ilya-palachev** [comment]
> Yes!

Thanks!
