### ISSUE TITLE
kobert로 squad 문제 해결을 위한 사용 문의

### ISSUE THREAD

**Issue by junho-one** [SKTBrain/KoBERT#3]
안녕하세요
알려주신 사이트를 참고해봤는데, 질문이 있어서 올립니다.
hugging face에 run_squad를 했을 때와 똑같은 에러가 나오는데

위 사이트에서는 모델에 인풋값을
model(input_ids, segment_ids, input_mask, start_positions, end_positions)
로 주는데

Kobert 모델에 인풋값은
model(input_ids, token_type_ids, input_mask)
이런 형식으로 주더라고요

이렇게 인풋에 차이가 나는데 어떻게 맞춰줄 수 있는지 조언을 좀 구할 수 있을까요?

**Comment by haven-jeon** [comment]
run_squad를 확인해 보진 않았지만. start_positions, end_positions을 보니 squad를 위해 hugging face BERT 모델을 wrapping한 함수로 보입니다.  해당 함수의 내부를 수정해 KoBERT API를 적용 하시면 가능하실거 같습니다.
