### ISSUE TITLE
fine tuning 시에 사용할 vocab을 따로 만들순 없나요?

### ISSUE THREAD

**Issue by dhsimpson** [SKTBrain/KoBERT#30]
안녕하세요! kobert 를 이용해 grammar error correction task 를 진행하고 있습니다.
제가 사용하는 데이터의 단어 중에 공개해 주신 모델의 vocab에 없는 단어가 많아 재현율이 현저히 떨어져서 제 데이터로 vocab을 만들고자 합니다.
제공된 토크나이저로 형태소 단위로 자른 후,
glounnlp의 counter 클래스에 input해 counter 를 형성해 보니
다시 음절 단위로 자르더라구요.( 형태소 string을 음절단위로 자릅니다 )
형태소 string을 그대로 이용해 counter를 형성한 뒤 vocab을 형성하고 싶은데, 혹시 sk brain 에선 vocab 형성을 어떻게 했는지 알려주실 수 있을까요?

긴 글 질문 읽어주셔 감사드립니다.

**Comment by haven-jeon** [comment]
KoBERT vocab은 대량의 위키 뉴스 텍스트로 sentencepiece tokenizer를 학습 후 생성 했습니다.
말씀 하신 형태소 단위로 vocab을 재작성 하신다면... KoBERT pre-training을 다시 해야 될것으로 예상됩니다.

**Comment by dhsimpson** [comment]
@haven-jeon  으으...그렇군요 감사합니다!!
