### ISSUE TITLE
KoBERT Pre-Training Procedure

### ISSUE THREAD

**Issue by xplip** [SKTBrain/KoBERT#35]
You've already provided some information on how you pre-trained KoBERT in the `README.md`, which is great. Would you mind also sharing how many training steps you trained for and what batch sizes and sequence lengths you used?

Thanks!

**Comment by haven-jeon** [comment]
During the learning process, there were various trials and errors, so the exact number of experimental steps is not known. However, for about two months, we used 16 V100 GPUs to fill all the memory and train.  The sequence length was set to 512.
