### ISSUE TITLE
Issue on train naver_review_classifications_pytorch_kobert.ipynb

### ISSUE THREAD

**Issue by LoveMeWithoutAll** [SKTBrain/KoBERT#38]
When running `naver_review_classifications_pytorch_kobert.ipynb` example, I got an error below.
In last section, `out = model(token_ids, valid_length, segment_ids)` code makes the error.
I have doubt where the expired api is used.
May I know get any information to solve the error from anyone?

```
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  """
0%
0/2344 [00:00<?, ?it/s]

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-24-e6a38b13095b> in <module>()
      9         valid_length= valid_length
     10         label = label.long().to(device)
---> 11         out = model(token_ids, valid_length, segment_ids)
     12         loss = loss_fn(out, label)
     13         loss.backward()

4 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in dropout(input, p, training, inplace)
    981     return (_VF.dropout_(input, p, training)
    982             if inplace
--> 983             else _VF.dropout(input, p, training))
    984 
    985 

TypeError: dropout(): argument 'input' (position 1) must be Tensor, not str
```

Here is the [link](https://colab.research.google.com/drive/1_Hsn7iXz6SygYjgmmvTF_QVBGf5klmlT?usp=sharing) for reproducing error.

**Comment by gatherheart** [comment]
Use `!pip install transformers==3
`
instead of  `!pip install transformers`

I tested and it works.

**Reference**
[huggingface issue #8879](https://github.com/huggingface/transformers/issues/8879)

**Comment by LoveMeWithoutAll** [comment]
> Use `!pip install transformers==3 `
> instead of `!pip install transformers`
> 
> I tested and it works.
> 
> **Reference**
> [huggingface issue #8879](https://github.com/huggingface/transformers/issues/8879)

It works very well. Thank you!
