### ISSUE TITLE
Training dataset size

### ISSUE THREAD

**Issue by tmtmaj** [SKTBrain/KoBERT#39]
안녕하세요. 공개해주신 모델 정말 잘 사용하고 있습니다. 

다른 언어 모델과의 비교를 위해 데이터셋에 대한 정보가 필요해서 질문을 올립니다.

훈련 데이터 셋의 크기를 알 수 있을까요? (약 몇 G 인지)

감사합니다.

**Comment by haven-jeon** [comment]
20GB 정도 데이터(raw 기준)를 사용했습니다.
