### ISSUE TITLE
한글 버트 데이터는 공유여부가 궁금합니다.

### ISSUE THREAD

**Issue by JoungheeKim** [SKTBrain/KoBERT#4]
안녕하세요? 
한글 버트를 제공해 주셔서 감사합니다.
한글 버트에 대해서 더 공부하고 싶은데 혹시 버트 트레이닝 했던 데이터를 공유가 가능하신지 여쭤보고 싶어서 연락드렸습니다.

감사합니다.

**Comment by haven-jeon** [comment]
위키 데이터와 전처리 하는 툴은 이곳에서 확인하시면 됩니다. 
https://github.com/attardi/wikiextractor

뉴스 텍스트의 경우 저작권이 있어 공유는 불가능합니다.
