### ISSUE TITLE
please modify requirement.txt

### ISSUE THREAD

**Issue by Hogaeng** [SKTBrain/KoBERT#40]
README.md의 How to use Pytorch 코드  중

> sequence_output, pooled_output = model(input_ids, input_mask, token_type_ids)

sequence_output, pooled_output이 torch.size가 아닌 str 타입으로 나오며 다음으로 진행이 되지 않습니다.

원인은 transformers 4.2로 인해 나타난 에러이며, requirement.txt에서

> transformers>=3.5

를

> transformers<4

로 바꿔주시길 바랍니다.

**Comment by haven-jeon** [comment]
#42
