### ISSUE TITLE
Using with PyTorch 마지막 부분 error

### ISSUE THREAD

**Issue by kimsijin33** [SKTBrain/KoBERT#43]
Using with PyTorch 
위 코드로 콜랩에서 실행하면 
마지막 코드에서 

        out = model(token_ids, valid_length, segment_ids) # 이부분에서 오류 납니다. 값이 텐서여야 한다고..

코드
for e in range(num_epochs):
    train_acc = 0.0
    test_acc = 0.0
    model.train()
    for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(tqdm_notebook(train_dataloader)):
        optimizer.zero_grad()
        token_ids = token_ids.long().to(device)
        segment_ids = segment_ids.long().to(device)
        valid_length= valid_length
        label = label.long().to(device)
        out = model(token_ids, valid_length, segment_ids)
        loss = loss_fn(out, label)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_grad_norm)
        optimizer.step()
        scheduler.step()  # Update learning rate schedule
        train_acc += calc_accuracy(out, label)
        if batch_id % log_interval == 0:
            print("epoch {} batch id {} loss {} train acc {}".format(e+1, batch_id+1, loss.data.cpu().numpy(), train_acc / (batch_id+1)))
    print("epoch {} train acc {}".format(e+1, train_acc / (batch_id+1)))
    model.eval()
    for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(tqdm_notebook(test_dataloader)):
        token_ids = token_ids.long().to(device)
        segment_ids = segment_ids.long().to(device)
        valid_length= valid_length
        label = label.long().to(device)
        out = model(token_ids, valid_length, segment_ids)
        test_acc += calc_accuracy(out, label)
    print("epoch {} test acc {}".format(e+1, test_acc / (batch_id+1)))

==================로그 log
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  """
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-22-e6a38b13095b> in <module>()
      9         valid_length= valid_length
     10         label = label.long().to(device)
---> 11         out = model(token_ids, valid_length, segment_ids)
     12         loss = loss_fn(out, label)
     13         loss.backward()

4 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in dropout(input, p, training, inplace)
    981     return (_VF.dropout_(input, p, training)
    982             if inplace
--> 983             else _VF.dropout(input, p, training))
    984 
    985 

TypeError: dropout(): argument 'input' (position 1) must be Tensor, not str
0%
0/2344 [00:00<?, ?it/s]

**Comment by haven-jeon** [comment]
transformers가 업데이트 되어서 나온 이슈 입니다. #40 적용 되었으니, 다시 설치 부탁드립니다.

**Comment by haven-jeon** [comment]
별다른 피드백이 없어 이슈 클로즈 합니다.
