### ISSUE TITLE
KoBERT를 실제 적용 하려면 어떻게 해야 하나요?

### ISSUE THREAD

**Issue by kimsijin33** [SKTBrain/KoBERT#44]
소스를 다운받은 상태인데요 
그리고 콜랩에서 한번 돌려보고 있습니다. 

다운받은 소스를 어떻게 사용하는지 몰라서요 
학습을 어떻게 시키고 

제가 인풋 데이터를 어떻게 넣고 결과를 어떻게 받는지 알 수 있을까요?

그리고 
이게 그럼 어떤 결과를 가져다 주는 모델인가요?
영어 -> 한글 번역?
용도가 뭔가요?

블로그 보면 혹시 이건가요?
2) Next Sentence Prediction(NSP)
두 문장을 주고 두 번째 문장이 글에서 첫 번째 문장의 바로 다음에 오는지 예측하는 방법이다.

**Comment by haven-jeon** [comment]
질문이 너무 방대하네요. BERT 페이퍼 일독을 권해드립니다. 

https://arxiv.org/abs/1810.04805
