### ISSUE TITLE
혹시 MLM 모델은 제공이 안될까 해서 문의드립니다

### ISSUE THREAD

**Issue by Aruie** [SKTBrain/KoBERT#46]
안녕하세요 

깃에 글남겨보는거 처음이네요...

혹시 학습하실때 사용한 MLM 모델의 pretrained weights 는 

받을 수 있는 방법이 없을까요??

MLM 모델부분을 만들어서 fine-tuning 해보긴 했는데

생각보다 데이터가 많이 필요한것도있고 

학습환경도 그리 넉넉치않아서

크게 차이가 나지않는다면 general 하게 학습된 가중치가 더 일반화에 좋지 않을까해서요

감사합니다!

**Comment by haven-jeon** [comment]
https://github.com/SKTBrain/KoBERT/blob/afc65d976e06dfc0556b4b62996203d1d77f24c6/kobert/pytorch_kobert.py#L35 코드 보시면 모델 파라메터 로컬 저장 경로가 있습니다. 그곳에서 가져다 쓰시면 됩니다.

**Comment by Aruie** [comment]
> https://github.com/SKTBrain/KoBERT/blob/afc65d976e06dfc0556b4b62996203d1d77f24c6/kobert/pytorch_kobert.py#L35
> 
> 코드 보시면 모델 파라메터 로컬 저장 경로가 있습니다. 그곳에서 가져다 쓰시면 됩니다.
