### ISSUE TITLE
저한테만 뜨는 에러인지

### ISSUE THREAD

**Issue by airshin11** [SKTBrain/KoBERT#47]
model, vocab  = get_pytorch_kobert_model() 엔터하면

OSError: Not found: "C:\Users\etfffff/kobert/kobert_news_wiki_ko_cased-1087f8699e.spiece": Illegal byte sequence Error #42 이라는 에러코드가 뜨는데요

**Comment by Minku-Koo** [comment]
KoBERT 설치 경로에 한글이 포함되어 나오는 에러 같습니다.

**Comment by haven-jeon** [comment]
감사합니다. 도움이 된거 같습니다. 해당 이슈는 클로즈 하겠습니다.
