### ISSUE TITLE
pretraining time 질문드립니다!

### ISSUE THREAD

**Issue by wonbeeny** [SKTBrain/KoBERT#48]
먼저 너무 좋은 자료 공유해주셔서 감사합니다.
pretraining 학습시 V100 GPU 32장을 사용하신 것으로 알고 있습니다.
500만 개의 문장을 해당 환경에서 학습하는데 어느 정도의 시간이 소요되는지 궁금합니다.
또한 epoch는 몇으로 설정했는지 궁금합니다.

감사합니다.

**Comment by haven-jeon** [comment]
README에 공개된 부분 이상으로는 확인해 드리기 어려울거 같습니다.

감사합니다.
