### ISSUE TITLE
컨버전 관련

### ISSUE THREAD

**Issue by kimsijin33** [SKTBrain/KoBERT#49]
구글 mutilingual BERT 로 만들어진 프로그램을
 koBert 로 전환 가능할까요?

**Comment by haven-jeon** [comment]
모델 로딩 부분하고 토크나이저 부분을 고치시면 가능할 것으로 보입니다.

**Comment by haven-jeon** [comment]
응답이 없는 관계로 클로즈 하겠습니다.
