### ISSUE TITLE
띄어쓰기 복원 관련(언더바)

### ISSUE THREAD

**Issue by jinulee-v** [SKTBrain/KoBERT#50]
안녕하세요, kobert를 이용 중인 학생입니다.
코버트를 이용하는 중에 원문 복원에 관해 문제가 생겨서 이슈 남깁니다.

언더바가 매 어절 처음에 들어가는 것까지는 이해가 되었는데, 문장 안에 언더바가 이미 포함되어 있을 때는 어떻게 처리해야 할 지 잘 모르겠습니다. 예를 들어,
"조선일보_홍길동 기자"
라는 입력을 토크나이저에 입력하면
`"_조선" "일보" "_" "홍" "길" "동" "_" "기자"` 
와 같 토큰화가 됩니다. 여기서 언더바만 있는 토큰 두개 중 어느 것이 언더바이고 어느 것이 어절의 처음을 나타내는 심볼인지 확인할 방법이 없습니다. 원문 복원을 위해서 어떤 방법이 있을지 궁금합니다.

**Comment by haven-jeon** [comment]
sentencepiece에서 띄어쓰기 용으로 쓰고 있는 "▁" (U+2581)는 키보드 입력이 가능한 _ 하고 다릅니다.
참고하시기 바랍니다.

**Comment by jinulee-v** [comment]
확인했습니다!
