### ISSUE TITLE
Config of KoBERT

### ISSUE THREAD

**Issue by detuvoldo** [SKTBrain/KoBERT#51]
Hi,

Thanks for releasing the model. I want to ask how I can get the config file of KoBert. For example, the config of BERT is like:

> BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.5.1",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

**Comment by haven-jeon** [comment]
You can check the config with the following code.

```
model, vocab  = get_pytorch_kobert_model()
model.config
```

**Comment by detuvoldo** [comment]
> You can check the config with the following code.
> 
> ```
> model, vocab  = get_pytorch_kobert_model()
> model.config
> ```

Thanks for your answer!
