### ISSUE TITLE
koBERT import Error

### ISSUE THREAD

**Issue by kimSooHyun950921** [SKTBrain/KoBERT#55]
torch-1.8.1+cu101 이상 버전에서는 
from kobert.pytorch_kobert import get_pytorch_kobert_model 에서
```
/usr/local/lib/python3.7/dist-packages/transformers/trainer_pt_utils.py in <module>()
     38     SAVE_STATE_WARNING = ""
     39 else:
---> 40     from torch.optim.lr_scheduler import SAVE_STATE_WARNING
     41 
     42 logger = logging.get_logger(__name__)

ImportError: cannot import name 'SAVE_STATE_WARNING' from 'torch.optim.lr_scheduler' (/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py)
```
에러가 납니다.
requirements.txt 에서의 torch 버전을 torch==1.7로 고정하면 좋을것같습니다!

**Comment by yw0nam** [comment]
gluonnlp==0.6.0에서는 

nlp.vocab.BERTVocab안에 from_sentencepiece  attribute가 존재하지않습니다.

gluonnlp==0.8.0으로 업그레이드하니 정상적으로 임포트됩니다.

**Comment by haven-jeon** [comment]
답변 감사합니다. 별다른 피드백이 없어 보여 해당 이슈는 클로즈 합니다.

**Comment by Haebuk** [comment]
> gluonnlp==0.6.0에서는
> 
> model, vocab = get_pytorch_kobert_model()에서
> nlp.vocab.BERTVocab안에 from_sentencepiece attribute가 존재하지않아 에러가 발생합니다.
> 
> gluonnlp==0.8.0으로 업그레이드하니 정상적으로 불러와 집니다.
위 사항을 진행해도,
get_pytorch_kobert_model에서 transformers를 import 할 때 동일한 이슈가 발생하는데, 
`pip install --user -q torch==1.4.0 -f https://download.pytorch.org/whl/cu101/torch_stable.html`
를 통해 torch를 1.4.0버전으로 바꾸니 되네요.
