### ISSUE TITLE
코드 실행시 커널이 죽습니다.

### ISSUE THREAD

**Issue by powerzist** [SKTBrain/KoBERT#57]
from kobert.pytorch_kobert import get_pytorch_kobert_model
또는
bertmodel, vocab = get_pytorch_kobert_model()

코드 실행 시 실행 되다가 끝까지 못가고 커널이 죽어버려서 다음과 같은 메세지를 띄웁니다.

The kernel appears to have died. It will restart automatically.

두 대의 서버에서 해당 코드를 실행해봤는데 한 대는 정상 작동하지만 다른 한 대는 위와 같은 메세지와 함께 커널이 죽어버리네요.

pip install -r requirements.txt 명령을 실행해서 버전도 모두 맞췄습니다.

이유가 뭘까요?

**Comment by haven-jeon** [comment]
두대중에 하나만 죽는건 환경이나 하드웨어 이슈일 가능성이 있어 보이네요..

**Comment by powerzist** [comment]
> 두대중에 하나만 죽는건 환경이나 하드웨어 이슈일 가능성이 있어 보이네요..

주피터 노트북을 사용 중인데 아무래도 메모리가 부족해서 발생하는 문제이지 않을까 싶습니다.
이럴 경우 max_buffer_size 옵션을 바꿔주면 된다는데 문제가 발생하는 서버에는 해당 설정이 인식이 되질 않네요.
이미 셋팅된 서버를 받은거라서 함부로 이것저것 만지기가 좀 그래서 일단은 그대로 두고 사용할 수 있는 방법을 찾아보다가,
코드 실행 순서들을 조금 바꾸어 보았더니 커널이 죽지 않고 실행이 되긴 했습니다.
특히 bertmodel, vocab = get_pytorch_kobert_model() 코드의 경우 using cached model 문구가 세 줄이 뜨는게 원래 실행 결과였는데 코드 순서를 바꾸다보니 두 줄만 뜨고 실행 완료되어서 어찌저찌 커널이 죽지 않고 실행이 되었네요. (세 줄이 뜨는게 원래 실행 결과였을 때는 두 줄까지 출력되고 나서 커널이 죽어버렸습니다.)
그런데 이건 어디까지나 추측일 뿐인게 정상 작동하는 다른 서버는 물론 max_buffer_size 설정이 인식이 되긴 하지만 default 값 그대로 사용해도 문제가 없었거든요. 물론 하드웨어 사양에 따라서 default 값이 다르게 적용된다면 설득력이 있겠지만 역시 제대로 확인해보지 않는 이상은 확신할 수는 없을 것 같습니다.

**Comment by haven-jeon** [comment]
해당 이슈는 KoBERT의 문제라 보기 어려운거 같습니다. 
하지만 https://github.com/SKTBrain/KoBERT/tree/master/kobert_hf 에서 허깅페이스로 작업된 코드를 사용하여 시도해보시면 어떨까 하네요.

**Comment by haven-jeon** [comment]
답변이 없는 관계로 해당 이슈는 클로즈 하겠습니다. 이슈 발생시 다시 오픈 부탁드립니다.
