### ISSUE TITLE
sentence pair classification을 하고 싶은데 진행 불가합니다 ㅠㅠ

### ISSUE THREAD

**Issue by ji0859** [SKTBrain/KoBERT#61]
안녕하세요. 하다가 진행이 불가능 하여 여쭈어 봅니다.. ㅠㅠ

kobert 로 비슷한 문장에 대하여 학습을 더 시키는 작업을 현재 naver영화 리뷰의 코드에서 조금씩 고치며 진행중입니다.

비슷한 문장을 학습시켜주기 위한 데이터 형식은 [[sent1, sent2 , label], [...], ....] 이러한 형식으로 존재합니다. </br>
예시 ) 
`['글쎄, 나는 그것에 관해 생각조차 하지 않았지만, 나는 너무 좌절했고, 결국 그에게 다시 이야기하게 되었다.', '나는 그와 다시 이야기하지 않았다.', '0']`

데이터 학습 시키기 위해 아래와 같이 진행하게 된다면 마지막 pair에서 False가 아닌 True를 줘야지 비슷한 문장에 대하여 학습이 되는 것으로 알아 그렇게 진행을 하게 될 경우 python assertion error 가 나게 됩니다. 

`[data_train = BERTDataset(data_list, 0, 1,2, tok, max_len, True, False)] `

혹시 비슷한 문장에 대하여 학습이 불가능 한가요?

**Comment by ji0859** [comment]
해결했습니다!

**Comment by BakChaewon** [comment]
안녕하세요. 
kobert로 감성분석 프로젝트 진행하다 같은 문제를 만나 구글링 하던중 해당 issue 발견하게 됐습니다.
혹시 어떻게 해결하셨는지 알 수 있을까요? 추가로 sentence pair 관련 task 진행시 BERTDataset에 sent_idx 인자를 어떻게 넣어주는게 맞을까요?
