### ISSUE TITLE
클래스 불균형데이터 학습

### ISSUE THREAD

**Issue by SeungGi-5** [SKTBrain/KoBERT#63]
안녕하세요, kobert를 이용해서 직접수집한 리뷰데이터에 대한 감성분석을 시도하고있습니다.
하지만 음식점 리뷰데이터의 특성상 긍정부분에 대한 리뷰가 더욱 많아 클래스 불균형으로인해 재현율이 다소 떨어지기때문에 그것을 해소하고자 임베딩벡터인 pooler를 이용하여 oversampling을 하고자했습니다.

하지만 pooler 데이터 그대로를 사용할수는없어 Numpy배열로 변환한뒤 oversampling기법인 smote를 이용하여 불균형 문제해소는 가능하지만 
벡터를 다시 문장형태로 변환할수있을까요? or numpy배열 형태인 임베딩벡터 데이터를 다시 학습에 사용할수있는방법이 있을까요?

kobert를 이용하여 클래스불균형 문제를 다루기위해서 어떤방법이 있을지 궁금합니다. 다소 두서없는 질문에 죄송합니다. 그리고 멋진 모델을 사용할수있게해주셔서 감사합니다!

**Comment by haven-jeon** [comment]
답변이 늦었네요. 

pooler는 class 레이블 수자로 벡터를 사영하기 위한 용도인데요. 이를 char 벡터 형태로 변환하는건 다소 모호한 결과를 내지 않을까 하는 생각이 듭니다.  유사한 방식으로 언어모델을 사용한 augmentation 방법을 사용하는건 어떨까 합니다. 


https://textattack.readthedocs.io/en/latest/2notebook/3_Augmentations.html

 감사합니다.
