### ISSUE TITLE
W2V처럼 문장을 임베딩하는 방법 문의

### ISSUE THREAD

**Issue by Haebuk** [SKTBrain/KoBERT#64]
안녕하세요.
아래 이슈와 동일한 task를 진행중인데, 현재 제 데이터에는 label이 없습니다.
KoBERT를 통해 마치 Word2Vec처럼 문장을 입력했을 때 label이 따로 없어도 유사도를 계산할 수 있는 임베딩 벡터로 바꿔주고 싶은데
어떻게 하면 좋을까요?

_Originally posted by @Haebuk in https://github.com/SKTBrain/KoBERT/issues/24#issuecomment-925470033_

**Comment by haven-jeon** [comment]
https://arxiv.org/abs/1908.10084 논문 참고하시기 바랍니다. 
감사합니다.

**Comment by Haebuk** [comment]
감사합니다.
