### ISSUE TITLE
get_pytorch_kobert_model 대신 kobert_hf 사용하는 것으로 바꾸는 방법에 대한 문의

### ISSUE THREAD

**Issue by jiwon199** [SKTBrain/KoBERT#68]
get_pytorch_kobert_model 불러오기 오류로 인해 https://github.com/SKTBrain/KoBERT/tree/master/kobert_hf 주소의 모델을 사용하는 것으로 코드를 급하게 바꾸는 중인데 어려움을 겪어서 질문 남깁니다. 
`tokenizer = get_tokenizer()`
`bertmodel, vocab = get_pytorch_kobert_model()`
를
`tokenizer = KoBERTTokenizer.from_pretrained('skt/kobert-base-v1')`
`bertmodel, vocab = get_kobert_model('skt/kobert-base-v1',tokenizer.vocab_file)`
 
으로 바꾸었는데, 
`tok = nlp.data.BERTSPTokenizer(tokenizer, vocab, lower=False)`
`data_train = BERTDataset(dataset_train, 0, 1,tok, max_len, True, False)`
`data_test = BERTDataset(dataset_test, 0, 1, tok, max_len, True, False)`
코드에서 TypeError: not a string 에러가 발생합니다. 어떻게 해결하면 좋을까요...?
 
 
![image](https://user-images.githubusercontent.com/53902714/141458127-455a32a0-5f9f-4117-90c1-f84a5206d979.png)

### class BERTDataset(Dataset):
    def __init__(self, dataset, sent_idx, label_idx, bert_tokenizer, max_len,
                 pad, pair):
        transform = nlp.data.BERTSentenceTransform(
            bert_tokenizer, max_seq_length=max_len, pad=pad, pair=pair)

        self.sentences = [transform([i[sent_idx]]) for i in dataset]
        self.labels = [np.int32(i[label_idx]) for i in dataset]

    def __getitem__(self, i):
        return (self.sentences[i] + (self.labels[i], ))

    def __len__(self):
        return (len(self.labels))
BERTDataset은 이 코드를 쓰고 있습니다.

**Comment by jiwon199** [comment]
자문자답인데 
`tok=tokenizer.tokenize
data_train = BERTDataset(dataset_train, 0, 1, tok,vocab, max_len, True, False)
data_test = BERTDataset(dataset_test,0, 1, tok,vocab,  max_len, True, False)`
로 바꾸고 BERTDataset 클래스 조금 수정하니까 해결됐습니다..

**Comment by jiwon199** [comment]
자문자답인데 
`tok=tokenizer.tokenize`
`data_train = BERTDataset(dataset_train, 0, 1, tok,vocab, max_len, True, False)`
`data_test = BERTDataset(dataset_test,0, 1, tok,vocab,  max_len, True, False)`
 로 바꾸고 BERTDataset 클래스 조금 수정하니까 해결됐습니다..

**Comment by hxxnmxn** [comment]
안녕하세요 비슷한 문제로 계속 시도중인데 혹시 BERTDataset은 어떻게 수정하셨는지 알 수 있을까요? ㅜㅜ

**Comment by jiwon199** [comment]
init 부분에서 
`def __init__(self, dataset, sent_idx, label_idx, bert_tokenizer,vocab, max_len,
                 pad, pair):
   
        transform = nlp.data.BERTSentenceTransform(
            bert_tokenizer, max_seq_length=max_len,vocab=vocab, pad=pad, pair=pair)`
로  vocab을 인자로  추가했습니다!

**Comment by khm950903** [comment]
> init 부분에서
> 
> def **init**(self, dataset, sent_idx, label_idx, bert_tokenizer,vocab, max_len, pad, pair): transform = nlp.data.BERTSentenceTransform( bert_tokenizer, max_seq_length=max_len,vocab=vocab, pad=pad, pair=pair)
> 
> 이렇게 vocab을 인자로 추가했습니다!

답변 감사합니다. ㅜㅜ

```
!pip install kobert_transformers
!pip install 'git+https://github.com/SKTBrain/KoBERT.git#egg=kobert_tokenizer&subdirectory=kobert_hf'
```
```
from kobert_tokenizer import KoBERTTokenizer
from kobert_transformers import get_kobert_model
```
```
tokenizer = KoBERTTokenizer.from_pretrained('skt/kobert-base-v1')
bertmodel = get_kobert_model()
vocab = tokenizer.vocab_file
```

저는 위의 코드로 모델과 토크나이저를 불러왔는데
제가 모델 불러오는 방식에 문제가 있는건지 알려주신 방법으로는 해결되지 않네요 ㅜㅜ

다시 한번 잘 고쳐서 시도해보겠습니다... 감사합니다!

**Comment by tacowasabii** [comment]
> init 부분에서
> 
> def **init**(self, dataset, sent_idx, label_idx, bert_tokenizer,vocab, max_len, pad, pair): transform = nlp.data.BERTSentenceTransform( bert_tokenizer, max_seq_length=max_len,vocab=vocab, pad=pad, pair=pair)
> 
> 이렇게 vocab을 인자로 추가했습니다!

혹시 vocab은 어떻게 정의했는지 좀 알 수 있을까요?

**Comment by jiwon199** [comment]
> @jiwon199
> 
> 혹시 vocab은 어떻게 정의했는지 좀 알 수 있을까요?

```tokenizer = KoBERTTokenizer.from_pretrained('skt/kobert-base-v1')
bertmodel, vocab = get_kobert_model('skt/kobert-base-v1',tokenizer.vocab_file)
입니다

**Comment by tacowasabii** [comment]
> > @jiwon199
> > 혹시 vocab은 어떻게 정의했는지 좀 알 수 있을까요?
> 
> 이렇게 정의했습니다 BERTDataset 코드도 바뀌어야 하는데 위에 참고하시면 될 것 같습니다!
> 
> ```
> tokenizer = KoBERTTokenizer.from_pretrained('skt/kobert-base-v1')
> bertmodel, vocab = get_kobert_model('skt/kobert-base-v1',tokenizer.vocab_file) 
> ```

get_kobert_model함수는 어디서 import 해온건가요? from kobert_tokenizer import get_kobert_model 이렇게 해봤는데 오류가 나서요.. 조금만 도움주시면 정말 감사하겠습니다

**Comment by tacowasabii** [comment]
> > @jiwon199
> > 혹시 vocab은 어떻게 정의했는지 좀 알 수 있을까요?
> 
> ```
> tokenizer = KoBERTTokenizer.from_pretrained('skt/kobert-base-v1')
> bertmodel, vocab = get_kobert_model('skt/kobert-base-v1',tokenizer.vocab_file) 
> ```
> 
> 이렇게 정의했습니다 BERTDataset 코드도 바뀌어야 하는데 위에 참고하시면 될 것 같습니다!

큰 도움이 됐습니다. 정말 감사합니다
그런데 마지막에 KoBERT 모델을 학습시키는 과정에서 아래와 같은 오류가 발생합니다.
TypeError: dropout(): argument 'input' (position 1) must be Tensor, not str
구글링을 해보니 transformer 버전에 따른 오류 같은데 기존에 사용했던 kobert에선 필요한 트랜스포머 버전이 3.6.0이었는데 kobert_hf에선 4.8.2로 업그레이드 되는 과정에서 생기는 문제 같습니다. 혹시 이 부분은 어떻게 해결하셨는지 여쭤봐도 될까요?

**Comment by jiwon199** [comment]
> > > @jiwon199
> > > 혹시 vocab은 어떻게 정의했는지 좀 알 수 있을까요?
> > 
> > 
> > ```
> > tokenizer = KoBERTTokenizer.from_pretrained('skt/kobert-base-v1')
> > bertmodel, vocab = get_kobert_model('skt/kobert-base-v1',tokenizer.vocab_file) 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 이렇게 정의했습니다 BERTDataset 코드도 바뀌어야 하는데 위에 참고하시면 될 것 같습니다!
> 
> 큰 도움이 됐습니다. 정말 감사합니다 그런데 마지막에 KoBERT 모델을 학습시키는 과정에서 아래와 같은 오류가 발생합니다. TypeError: dropout(): argument 'input' (position 1) must be Tensor, not str 구글링을 해보니 transformer 버전에 따른 오류 같은데 기존에 사용했던 kobert에선 필요한 트랜스포머 버전이 3.6.0이었는데 kobert_hf에선 4.8.2로 업그레이드 되는 과정에서 생기는 문제 같습니다. 혹시 이 부분은 어떻게 해결하셨는지 여쭤봐도 될까요?

https://github.com/jiwon199/kobert_multi-classification
저는 kobert를 사용해서 다중클래스분류 작업을 하였는데,데이터부분만 변경하여서 깃허브에 코드를 올렸습니다. 참고하셔서 진행중인 프로젝트에 맞게 변형하시면 될 것 같습니다.
