### ISSUE TITLE
KoBERT설치시, python 최소 버전

### ISSUE THREAD

**Issue by diagram298** [SKTBrain/KoBERT#70]
분명 아까까지만해도 잘 로드되었는데 현재는 다음과 같은 오류가 뜨면서 이용이 안됩니다. 
구글코랩에서 실행중이고 관련처리를 해봤는데 쉽지않네요 .. 
어떻게 해야 다시 정상적으로 이용할 수 있을지 ..
![image](https://user-images.githubusercontent.com/93654012/144188181-7542dd84-36b9-43af-95af-1ddc62216f31.png)

**Comment by bage79** [comment]
> 분명 아까까지만해도 잘 로드되었는데 현재는 다음과 같은 오류가 뜨면서 이용이 안됩니다. 구글코랩에서 실행중이고 관련처리를 해봤는데 쉽지않네요 .. 어떻게 해야 다시 정상적으로 이용할 수 있을지 .. ![image](https://user-images.githubusercontent.com/93654012/144188181-7542dd84-36b9-43af-95af-1ddc62216f31.png)

답변이 늦어서 죄송합니다.
코드를 리팩토링하면서, 최소 Python 버전을 `3.8.5`로 해두어 생긴 문제였습니다.
기존 README에 표기된 대로 최소 Python 버전을 `3.6`으로 돌렸습니다.
https://github.com/SKTBrain/KoBERT/commit/1a230ea56d760edf4a86dfd447fa0915052baa8a

다시 실행해 보시고, 피드백 부탁드립니다.

**Comment by bage79** [comment]
추가 피드백이 없어서 이 이슈를 클로즈합니다.
