### ISSUE TITLE
onnxruntime==0.3.0 설치에 관한 문의

### ISSUE THREAD

**Issue by EZYOON** [SKTBrain/KoBERT#75]
## 🐛 Bug
onnxruntime==0.3.0 설치 오류를 해결할 수 없습니다

조언이 필요합니다!!!🙏

## To Reproduce
![image](https://user-images.githubusercontent.com/44804022/148744139-cd199d5e-ab52-4510-91ef-2edc153ccef4.png)
* pip install git+https://git@github.com/SKTBrain/KoBERT.git@master 실패

![image](https://user-images.githubusercontent.com/44804022/148742865-05dc6211-c2cb-4fa0-8000-dd24c3f16c89.png)
* git clone 실패

수동으로 onnxruntime 0.3.0 버전을 설치하기 위해 whl 파일을 다운받았습니다
![image](https://user-images.githubusercontent.com/44804022/148742990-6a7c2c76-08a4-4134-92ee-fa48dca100b6.png)

그럼에도 설치에 실패했습니다..

버그를 재현하기 위한 재현절차를 작성해주세요.

1. pip install git+https://git@github.com/SKTBrain/KoBERT.git@master

## Expected behavior
kobert requirement 설치

## Environment
* GCP vm 인스턴스
* Ubuntu 20.04 LTS
* python 3.7.12

## Additional context
같은 오류를 겪으신 분들은 어떻게  onnxruntime을 설치하셨나요?
도움이 절실합니다 🥲

**Comment by HongKyoungIn** [comment]
다들 어떻게 설치하셨나요..

**Comment by HongKyoungIn** [comment]
주피터노트북으로 실행하려는데 오류가 발생합니다.. 설치하는 과정에서

**Comment by bage79** [comment]
@EZYOON @HongKyoungIn 님, 불편을 드려 죄송합니다.
저희가 개발할 때 사용되었던 `onnx 0.3.0`이 pypi에서 deprecated 되면서 발생한 문제로 보이며, 
pip가 사용하는 `index-url`에 따라서 설치가 가능한 경우도 있고, 안 되는 경우도 있을 것으로 추측됩니다.

python 3.6 ~ 3.8 까지 모두 사용 가능한 `onnx 1.8.0` 버전으로 모델을 다시 업로드 하였고, 설정 및 예제 코드도 업데이트하였습니다.
pip 로 다시 한번 설치하여 확인 부탁드립니다.

**Comment by HongKyoungIn** [comment]
![111](https://user-images.githubusercontent.com/88764725/149097763-b6458a1f-0e00-4531-b723-e0c7d45094a8.JPG)
이번엔 이런 오류가 납니다.

**Comment by bage79** [comment]
@HongKyoungIn 님, 
numpy 를 삭제하시거나, pyenv 등 가상환경을 새로 만드셔서 다시 확인해주시면 좋을 것 같습니다.
그리고 가상환경 사용여부, python 버전, pip 버전등도 표시 부탁드립니다.

혹시 문제가 지속된다면, 새로운 이슈로 등록 부탁드립니다.
현재 이슈와는 다른 numpy dependency  문제로 보입니다.

**Comment by HongKyoungIn** [comment]
주피터 노트북으로 파이썬 3.7버전 사용중입니다. 주피터로 오늘 가상환경 새로 만들었는데 아무래도 onnxruntime 1.8.0이랑 나머지 버전들이랑 numpy 의존성 충돌이 일어나는거 같은데 1.8.0말고 다른 버전으로 해야할까요?

**Comment by bage79** [comment]
@HongKyoungIn 
ubuntu 18.04 LTS 에서 가상 환경을 새로 생성하여 `pip install` 한 결과인데,  numpy 의존성 문제가 발생하지 않았습니다.
onnxruntime 버전과 관계 없는 이슈로 보입니다.

![image](https://user-images.githubusercontent.com/304911/149127379-0aca6636-1b3a-46cc-85a0-98edf6cd7536.png)
![image](https://user-images.githubusercontent.com/304911/149127457-be78ed99-7ec9-4566-a3b9-d6da5e39519e.png)
![image](https://user-images.githubusercontent.com/304911/149127482-ae36c740-7427-4b6f-a25f-a27697b27db0.png)

**Comment by HongKyoungIn** [comment]
@bage79 아나콘다나 주피터노트북의 문제인지 모르겠네요.. 버전을 0.5.0으로 하니깐 되긴 되는데 왜 안될까요ㅠㅠ

![1](https://user-images.githubusercontent.com/88764725/149136064-417d599f-c793-4a9c-b7fe-9ba28f609df6.JPG)
![2](https://user-images.githubusercontent.com/88764725/149136075-3d6313a5-acb7-44a8-b968-cfb6338eaabc.JPG)
![3](https://user-images.githubusercontent.com/88764725/149136079-5f6564b4-dc2e-4d57-8f13-1c71f7ac853c.JPG)
![4](https://user-images.githubusercontent.com/88764725/149136084-033e2b0c-a4a9-4260-b13d-201522692be2.JPG)

**Comment by HongKyoungIn** [comment]
![5](https://user-images.githubusercontent.com/88764725/149136258-cddfae6c-a619-4e7a-8d59-7cfe3945e55f.JPG)

**Comment by EZYOON** [comment]
@bage79 
좋은 모델 공개해주신 것도 감사한데 지속적인 이슈 모니터링으로 빠른 피드백주셔서 정말 감사합니다 

onnx 1.8.0 버전으로 다시 업로드해주신 덕분에 이슈를 해결할 수 있었고 환경 셋팅을 완료했습니다!
다시 한번 감사드립니다 !!!! 👍👍👍

**Comment by HongKyoungIn** [comment]
@bage79 몇번 시도해보니 뭔가 아나콘다인지 주피터노트북인지 모르겠는데 다운받는 버전의 차이가 있네요. 일단 mxnet이 1.9.0의 버전이 없네요.. 버전을 맞춰야 할 거 같네요.

**Comment by HongKyoungIn** [comment]
버전을 
boto3 - 1.15.18
gluonnlp - 0.10.0
mxnet - 1.7.0.post2
onnxruntime - 1.8.0
sentencepiece - 0.1.96
torch - 1.10.1
transformers - 3.0.2

이렇게 주니까 되네요

**Comment by bage79** [comment]
@HongKyoungIn 님, 
윈도우와 리눅스 차이가 가능한 버전 차이가 발생할 수 있을 것 같습니다. pip로 설치 가능한 버전을 확인하시려면, https://pypi.org/simple/onnxruntime/ 를 참고하실 수 있어요.

그리고 찾으신 버전 정보는 추후에 윈도우 관련 문의가 오면, 안내해드리도록 하겠습니다. 
감사합니다.

**Comment by bage79** [comment]
@EZYOON 님,
잘 해결되셔서 다행이네요.
onnxruntime 설치 관련 문제는 해결된 것으로 보여서 이 이슈는 Close합니다.

**Comment by HongKyoungIn** [comment]
boto3 - 1.15.18
gluonnlp - 0.10.0
mxnet - 1.7.0.post2
onnxruntime - 0.5.0
sentencepiece - 0.1.96
torch - 1.10.1
transformers - 3.0.2

버전 수정합니다. 위의 버전으로 설치해야 합니다.
