### ISSUE TITLE
[BUG] BERTClassifier drop_out rate에러

### ISSUE THREAD

**Issue by Danden1** [SKTBrain/KoBERT#78]
## 🐛 Bug
네이버 리뷰코드에서 BERTClassifier의
dr_rate를 None이나 0.0으로 하면 오류가 발생합니다.

## To Reproduce

![image](https://user-images.githubusercontent.com/13817715/158955275-f8bf727e-649a-4144-ae4c-e604d1ab98e8.png)

또는

![image](https://user-images.githubusercontent.com/13817715/158955303-e7166fdf-3844-495e-ae44-c46406159296.png)

로 설정하면,

![image](https://user-images.githubusercontent.com/13817715/158955245-b61d0d74-9b91-4c4d-87d7-4b0c479da846.png)

이와 같은 오류가 뜹니다.

    if self.dr_rate:
            out = self.dropout(pooler)
    else:
            out = pooler

    return self.classifier(out)

로 고쳐야 할 것 같습니다.

**Comment by bage79** [comment]
@Danden1 
오류로 인해, 불편을 드려서 죄송합니다.

말씀하신 내용을 반영하여 커밋하였습니다.
https://github.com/SKTBrain/KoBERT/commit/e1f2f37055e7460d8427f6912579c0162cb69831

감사합니다. 😍
