### ISSUE TITLE
[Train] Train 과정 에러

### ISSUE THREAD

**Issue by jamani135** [SKTBrain/KoBERT#79]
안녕하세요.

현재 코랩 환경에서 문서요약 태스크를 실험하고 있습니다. 

train 과정에서 아래와 같은 에러가 발생해 질문 드립니다.

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/72781125/164004223-85373bf4-d55f-45cf-b4a2-cbf295ab2621.png">

혹시 해결 방법이 있을까요??

**Comment by bage79** [comment]
@jamani135 

오류 로그로만 봤을때는, "decoder_input_ids" 를 받을 수 없다는 메시지입니다.
BERT의 경우 encoder 모델이기 때문에 decoder 자체가 없고, 문장을 생성하기 어렵습니다.
따라서 문서요약이라면 KoBART를 사용하셔야 할 것 같습니다.

아래 링크를 참고하셔서, 코드를 수정해 보시면 좋겠습니다.
• https://github.com/SKT-AI/KoBART
• https://github.com/seujung/KoBART-summarization

**Comment by bage79** [comment]
추가적인 코멘트가 없어서 이슈를 close합니다.
