### ISSUE TITLE
Got very bad result when fine-tune KoBERT on YNAT dataset

### ISSUE THREAD

**Issue by conan1024hao** [SKTBrain/KoBERT#85]
I am using few models for fine-tuning. On YNAT(KLUE-TC) task, KoBERT got very bad result when other models perform ok.

| | macro f1 
|--|--
mbert|0.802 |
xlm-roberta-base| 0.831| 
kobert-base| 0.447|
klue-bert-base| 0.848| 

KoBERT model I used: https://huggingface.co/monologg/kobert-lm
fine-tuning code: I am using transformers' `Trainer`, `AutoTokenizer` and `AutoModelForSequenceClassification`

Is `AutoModelForSequenceClassification` not supported by your model?

**Comment by bage79** [comment]
@conan1024hao 
Please use the `https://huggingface.co/skt/kobert-base-v1` model.
There are many `kobert` models in the Huggingface hub.
