### ISSUE TITLE
pytorch_pretrained_bert 라이브러리 사용 관련해서 문의드립니다.

### ISSUE THREAD

**Issue by inspirit941** [SKTBrain/KoBERT#9]
koBERT를 사용해보고 싶은 일이 있어서 fork하고 작업하다가 궁금한 점이 생겨 문의드립니다.

pytorch로 kobert 모델을 불러오는 pytorch_kobert.py에

```python
from pytorch_pretrained_bert import BertModel, BertConfig
```

부분이 있는데, pytorch_pretrained_bert 라이브러리는 2019년 4월 이후로 업데이트를 멈췄고
transformers라는 라이브러리에 통합된 것으로 보입니다.

https://github.com/huggingface/transformers

개인적으로 fork한 뒤 필요한 기능을 넣을 때는
pytorch_pretrained_bert보다 transformers가 필요한 기능을 찾아보기 쉬워서 transformers를 사용했는데,
혹시 pytorch_pretrained_bert 라이브러리를 계속 사용하는 이유가 있을까요?

만약 그렇지 않다면, pytorch_pretrained_bert 라이브러리를 사용하는 것보다는
통합된 버전인 transformers 패키지를 사용하는 것도 좋지 않을까 싶어 제안도 드리고 싶습니다.
```python
from transformers import BertModel, BertConfig
```

감사합니다.

**Comment by haven-jeon** [comment]
PR 주시면 어떨까요?

**Comment by haven-jeon** [comment]
감사합니다. PR 머지 했습니다.
